export * from './administracinDeUsuarios.service';
import { AdministracinDeUsuariosService } from './administracinDeUsuarios.service';
export * from './autenticacin.service';
import { AutenticacinService } from './autenticacin.service';
export * from './categoras.service';
import { CategorasService } from './categoras.service';
export * from './conceptos.service';
import { ConceptosService } from './conceptos.service';
export * from './cuentas.service';
import { CuentasService } from './cuentas.service';
export * from './partidas.service';
import { PartidasService } from './partidas.service';
export * from './perodos.service';
import { PerodosService } from './perodos.service';
export const APIS = [AdministracinDeUsuariosService, AutenticacinService, CategorasService, ConceptosService, CuentasService, PartidasService, PerodosService];
