/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { EntryUpdateRequest } from '../model/entryUpdateRequest';
// @ts-ignore
import { OneOffEntryRequest } from '../model/oneOffEntryRequest';
// @ts-ignore
import { PeriodEntry } from '../model/periodEntry';
// @ts-ignore
import { ProblemDetail } from '../model/problemDetail';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class PartidasService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Agregar una partida puntual
     * Crea una partida de origen &#x60;ONE_OFF&#x60; en un período abierto. Figura solo en ese período: no se copia a otros ni toca ningún Concepto. Responde con la partida y sus valores derivados, con la misma forma que la vista del mes. Orden en que se evalúa: formato de la ruta y del cuerpo (400), período inexistente (404), período cerrado (409), y después vencimiento, cuenta y categoría (400).
     * @endpoint post /api/periods/{period}/entries
     * @param period Período, como YYYY-MM.
     * @param oneOffEntryRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public createOneOffEntry(period: string, oneOffEntryRequest: OneOffEntryRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<PeriodEntry>;
    public createOneOffEntry(period: string, oneOffEntryRequest: OneOffEntryRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PeriodEntry>>;
    public createOneOffEntry(period: string, oneOffEntryRequest: OneOffEntryRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PeriodEntry>>;
    public createOneOffEntry(period: string, oneOffEntryRequest: OneOffEntryRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (period === null || period === undefined) {
            throw new Error('Required parameter period was null or undefined when calling createOneOffEntry.');
        }
        if (oneOffEntryRequest === null || oneOffEntryRequest === undefined) {
            throw new Error('Required parameter oneOffEntryRequest was null or undefined when calling createOneOffEntry.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/periods/${this.configuration.encodeParam({name: "period", value: period, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/entries`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PeriodEntry>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: oneOffEntryRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Editar una partida
     * Cambia una partida pendiente de un período abierto. En una partida sin Concepto edita nombre, categoría, cuenta, vencimiento y presupuestado, y no la marca como editada. En una recurrente edita solo el presupuestado (≥ 0) y la marca como editada, para que un cambio del monto vigente del Concepto no la pise; enviar el mismo monto no cambia nada, y cualquier otro dato (incluso junto con el presupuestado) es 409 FIELD_NOT_EDITABLE y no cambia nada. No toca otras partidas ni el Concepto. Solo cambia lo que se envía: un campo omitido o &#x60;null&#x60; no cambia, y la categoría se vacía con &#x60;clearCategory&#x60;. El tipo no se edita. Con movimientos, la cuenta solo cambia por otra de la misma moneda. Orden en que se evalúa: formato del cuerpo (400), partida inexistente o ajena (404), período cerrado (409), partida consolidada (409), dato no editable (409), vencimiento, cuenta y categoría (400), y moneda con movimientos (409).
     * @endpoint patch /api/entries/{id}
     * @param id 
     * @param entryUpdateRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public updateEntry(id: number, entryUpdateRequest: EntryUpdateRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<PeriodEntry>;
    public updateEntry(id: number, entryUpdateRequest: EntryUpdateRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PeriodEntry>>;
    public updateEntry(id: number, entryUpdateRequest: EntryUpdateRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PeriodEntry>>;
    public updateEntry(id: number, entryUpdateRequest: EntryUpdateRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateEntry.');
        }
        if (entryUpdateRequest === null || entryUpdateRequest === undefined) {
            throw new Error('Required parameter entryUpdateRequest was null or undefined when calling updateEntry.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/entries/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int64"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PeriodEntry>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: entryUpdateRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
