/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos de una cuenta, para el alta y para la edición (reemplaza todos los campos). En la edición, los campos que no se pueden cambiar se envían con su valor actual.
 */
export interface AccountRequest { 
    /**
     * Nombre, único por usuario sin distinguir mayúsculas. Se guarda sin espacios en los extremos.
     */
    name: string;
    /**
     * Tipo de cuenta.
     */
    type: AccountRequest.TypeEnum;
    /**
     * Moneda de la cuenta.
     */
    currency: AccountRequest.CurrencyEnum;
    /**
     * Desde cuándo se lleva la cuenta: entre el primer día del período inicial del usuario y hoy, ambos inclusive.
     */
    openingDate: string;
    /**
     * Saldo al comienzo de la fecha de apertura, con hasta 2 decimales. Puede ser negativo.
     */
    initialBalance: number;
}
export namespace AccountRequest {
    export const TypeEnum = {
        Bank: 'BANK',
        DigitalWallet: 'DIGITAL_WALLET',
        Cash: 'CASH',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const CurrencyEnum = {
        Ars: 'ARS',
        Usd: 'USD',
    } as const;
    export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];
}


