/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountEditability } from './accountEditability';


/**
 * Una cuenta del usuario, con su saldo actual y qué campos se pueden editar.
 */
export interface AccountResponse { 
    id: number;
    name: string;
    type: AccountResponse.TypeEnum;
    currency: AccountResponse.CurrencyEnum;
    openingDate: string;
    initialBalance: number;
    /**
     * Saldo a hoy (RN-35): saldo inicial más movimientos y transferencias con fecha hasta hoy. Puede ser negativo.
     */
    currentBalance: number;
    /**
     * Edición de los campos que no son siempre editables. El nombre y el tipo siempre se pueden editar.
     */
    editability: AccountEditability;
}
export namespace AccountResponse {
    export const TypeEnum = {
        Bank: 'BANK',
        DigitalWallet: 'DIGITAL_WALLET',
        Cash: 'CASH',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const CurrencyEnum = {
        Ars: 'ARS',
        Usd: 'USD',
    } as const;
    export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];
}


