/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldEditability } from './fieldEditability';


/**
 * Qué campos condicionados (RN-33) se pueden editar hoy.
 */
export interface AccountEditability { 
    currency: FieldEditability;
    initialBalance: FieldEditability;
    openingDate: FieldEditability;
}

