/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetItemGeneration } from './budgetItemGeneration';


/**
 * Un Concepto recién creado, con el resumen de las partidas que generó.
 */
export interface BudgetItemResponse { 
    id: number;
    name: string;
    kind: BudgetItemResponse.KindEnum;
    defaultAccountId: number;
    /**
     * Moneda del Concepto: la de su cuenta por defecto (RN-04).
     */
    currency: BudgetItemResponse.CurrencyEnum;
    categoryId?: number | null;
    periodicity: BudgetItemResponse.PeriodicityEnum;
    dueDay: number;
    dueMonthOffset: number;
    startPeriod: string;
    endPeriod?: string | null;
    estimationRule: BudgetItemResponse.EstimationRuleEnum;
    currentAmount: number;
    /**
     * Partidas generadas al crear el Concepto (RN-13).
     */
    generation: BudgetItemGeneration;
}
export namespace BudgetItemResponse {
    export const KindEnum = {
        Income: 'INCOME',
        Expense: 'EXPENSE',
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
    export const CurrencyEnum = {
        Ars: 'ARS',
        Usd: 'USD',
    } as const;
    export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];
    export const PeriodicityEnum = {
        Monthly: 'MONTHLY',
        Bimonthly: 'BIMONTHLY',
        Quarterly: 'QUARTERLY',
        Semiannual: 'SEMIANNUAL',
        Annual: 'ANNUAL',
    } as const;
    export type PeriodicityEnum = typeof PeriodicityEnum[keyof typeof PeriodicityEnum];
    export const EstimationRuleEnum = {
        LastValue: 'LAST_VALUE',
        AverageLast3: 'AVERAGE_LAST_3',
    } as const;
    export type EstimationRuleEnum = typeof EstimationRuleEnum[keyof typeof EstimationRuleEnum];
}


