/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Un Concepto en la lista (HU-14). El estado y las cuotas se calculan en el backend contra el período actual (D-27).
 */
export interface BudgetItemListItem { 
    id: number;
    name: string;
    kind: BudgetItemListItem.KindEnum;
    defaultAccountId: number;
    defaultAccountName: string;
    /**
     * Moneda del Concepto: la de su cuenta por defecto (RN-04).
     */
    currency: BudgetItemListItem.CurrencyEnum;
    categoryId?: number | null;
    categoryName?: string | null;
    periodicity: BudgetItemListItem.PeriodicityEnum;
    dueDay: number;
    dueMonthOffset: number;
    estimationRule: BudgetItemListItem.EstimationRuleEnum;
    currentAmount: number;
    startPeriod: string;
    /**
     * Último período posible. En un Concepto en cuotas, el de la última cuota.
     */
    endPeriod?: string | null;
    /**
     * Total de cuotas, o nulo si no es en cuotas (RN-14).
     */
    installmentsTotal?: number | null;
    /**
     * Cuota que corresponde al período de inicio, o nulo si no es en cuotas.
     */
    firstInstallmentNumber?: number | null;
    /**
     * ACTIVE: ya empezó y no terminó. FINISHED: su fin es anterior al período actual. SCHEDULED: empieza después del período actual.
     */
    status: BudgetItemListItem.StatusEnum;
    /**
     * Cuota que corresponde al período actual. Solo en un Concepto en cuotas con estado ACTIVE; nulo en los demás casos.
     */
    currentInstallment?: number | null;
    /**
     * Cuotas posteriores a la actual (0 en la última). Solo en un Concepto en cuotas con estado ACTIVE; nulo en los demás casos.
     */
    installmentsRemaining?: number | null;
}
export namespace BudgetItemListItem {
    export const KindEnum = {
        Income: 'INCOME',
        Expense: 'EXPENSE',
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
    export const CurrencyEnum = {
        Ars: 'ARS',
        Usd: 'USD',
    } as const;
    export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];
    export const PeriodicityEnum = {
        Monthly: 'MONTHLY',
        Bimonthly: 'BIMONTHLY',
        Quarterly: 'QUARTERLY',
        Semiannual: 'SEMIANNUAL',
        Annual: 'ANNUAL',
    } as const;
    export type PeriodicityEnum = typeof PeriodicityEnum[keyof typeof PeriodicityEnum];
    export const EstimationRuleEnum = {
        LastValue: 'LAST_VALUE',
        AverageLast3: 'AVERAGE_LAST_3',
    } as const;
    export type EstimationRuleEnum = typeof EstimationRuleEnum[keyof typeof EstimationRuleEnum];
    export const StatusEnum = {
        Active: 'ACTIVE',
        Finished: 'FINISHED',
        Scheduled: 'SCHEDULED',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


