/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Resumen de las partidas que generó el alta: una por período que corresponde, desde el inicio hasta el horizonte o el fin.
 */
export interface BudgetItemGeneration { 
    entryCount: number;
    /**
     * Período de la primera partida generada.
     */
    firstPeriod: string;
    /**
     * Período de la última partida generada.
     */
    lastPeriod: string;
    /**
     * Vencimiento de la primera partida (RN-12). Con desfase −1 cae en el mes anterior a su período.
     */
    firstDueDate: string;
}

