/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Cuántas partidas pendientes de períodos abiertos tiene el Concepto, calculado en el backend (RN-15). Una partida parcial, con movimientos, cuenta como pendiente.
 */
export interface BudgetItemEntryCounts { 
    /**
     * Pendientes no editadas: las que un cambio de monto vigente reemplaza.
     */
    pendingNotManual: number;
    /**
     * Pendientes editadas a mano: un cambio de monto vigente no las toca y siguen editadas.
     */
    pendingManual: number;
}

