/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos para crear un Concepto (RN-10), recurrente o en cuotas (RN-14). Con `installmentsTotal` es un plan de cuotas: el período de fin no se informa, se calcula como el inicio más (total − primera cuota) pasos de la periodicidad.
 */
export interface BudgetItemRequest { 
    /**
     * Nombre. Se guarda sin espacios en los extremos. Puede repetirse.
     */
    name: string;
    /**
     * Tipo: ingreso o gasto. No se edita después.
     */
    kind: BudgetItemRequest.KindEnum;
    /**
     * Cuenta por defecto, del usuario. Define la moneda del Concepto y de sus partidas.
     */
    defaultAccountId: number;
    /**
     * Categoría del usuario. Opcional.
     */
    categoryId?: number | null;
    /**
     * Periodicidad (RN-11). No se edita después.
     */
    periodicity: BudgetItemRequest.PeriodicityEnum;
    /**
     * Día de vencimiento. Si el mes no lo tiene, vence su último día (RN-12).
     */
    dueDay: number;
    /**
     * Desfase de mes: 0 si vence en el mes del período, −1 si vence el mes anterior.
     */
    dueMonthOffset: BudgetItemRequest.DueMonthOffsetEnum;
    /**
     * Primer período con partida (YYYY-MM): entre el primer período abierto y el horizonte. No se edita después.
     */
    startPeriod: string;
    /**
     * Último período posible (YYYY-MM), igual o posterior al de inicio. Puede superar el horizonte. Sin él, el Concepto no tiene fin. En un Concepto en cuotas no se informa: se calcula.
     */
    endPeriod?: string | null;
    /**
     * Cómo se estiman las partidas siguientes al consolidar (RN-26).
     */
    estimationRule: BudgetItemRequest.EstimationRuleEnum;
    /**
     * Monto vigente, con hasta 2 decimales: el presupuestado de las partidas que se generan.
     */
    currentAmount: number;
    /**
     * Total de cuotas (RN-14). Si se informa, el Concepto es en cuotas y el fin se calcula. No se edita después.
     */
    installmentsTotal?: number | null;
    /**
     * Número de la primera cuota, la que corresponde al período de inicio: entre 1 y el total. Permite cargar un plan ya empezado. Por defecto 1; solo se informa junto con el total. No se edita después.
     */
    firstInstallmentNumber?: number | null;
}
export namespace BudgetItemRequest {
    export const KindEnum = {
        Income: 'INCOME',
        Expense: 'EXPENSE',
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
    export const PeriodicityEnum = {
        Monthly: 'MONTHLY',
        Bimonthly: 'BIMONTHLY',
        Quarterly: 'QUARTERLY',
        Semiannual: 'SEMIANNUAL',
        Annual: 'ANNUAL',
    } as const;
    export type PeriodicityEnum = typeof PeriodicityEnum[keyof typeof PeriodicityEnum];
    export const DueMonthOffsetEnum = {
        NUMBER_0: 0,
        NUMBER_MINUS_1: -1,
    } as const;
    export type DueMonthOffsetEnum = typeof DueMonthOffsetEnum[keyof typeof DueMonthOffsetEnum];
    export const EstimationRuleEnum = {
        LastValue: 'LAST_VALUE',
        AverageLast3: 'AVERAGE_LAST_3',
    } as const;
    export type EstimationRuleEnum = typeof EstimationRuleEnum[keyof typeof EstimationRuleEnum];
}


