/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldEditability } from './fieldEditability';


/**
 * Qué datos de un Concepto no se pueden editar (RN-15, S-12).
 */
export interface BudgetItemEditability { 
    kind: FieldEditability;
    periodicity: FieldEditability;
    startPeriod: FieldEditability;
    endPeriod: FieldEditability;
    installments: FieldEditability;
}

