/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetItemEntryCounts } from './budgetItemEntryCounts';
import { BudgetItemEditability } from './budgetItemEditability';


/**
 * Un Concepto con qué datos se pueden editar y cuántas de sus partidas alcanzaría un cambio de monto vigente (RN-15). En un Concepto en cuotas, `endPeriod` es el período de la última cuota, calculado (RN-14).
 */
export interface BudgetItemDetail { 
    id: number;
    name: string;
    kind: BudgetItemDetail.KindEnum;
    defaultAccountId: number;
    /**
     * Moneda del Concepto: la de su cuenta por defecto (RN-04). La cuenta por defecto solo puede cambiarse por otra de esta moneda.
     */
    currency: BudgetItemDetail.CurrencyEnum;
    categoryId?: number | null;
    periodicity: BudgetItemDetail.PeriodicityEnum;
    dueDay: number;
    dueMonthOffset: number;
    startPeriod: string;
    /**
     * Último período posible. En un Concepto en cuotas, el de la última cuota.
     */
    endPeriod?: string | null;
    /**
     * Total de cuotas, o nulo si no es en cuotas (RN-14).
     */
    installmentsTotal?: number | null;
    /**
     * Cuota que corresponde al período de inicio, o nulo si no es en cuotas.
     */
    firstInstallmentNumber?: number | null;
    estimationRule: BudgetItemDetail.EstimationRuleEnum;
    currentAmount: number;
    /**
     * Los datos que nunca se editan (RN-15), con el motivo. El resto se edita siempre.
     */
    editability: BudgetItemEditability;
    /**
     * Partidas del Concepto en períodos abiertos que un cambio de monto vigente reemplaza o respeta. Las consolidadas y las de períodos cerrados no cuentan: nunca se tocan.
     */
    entryCounts: BudgetItemEntryCounts;
}
export namespace BudgetItemDetail {
    export const KindEnum = {
        Income: 'INCOME',
        Expense: 'EXPENSE',
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
    export const CurrencyEnum = {
        Ars: 'ARS',
        Usd: 'USD',
    } as const;
    export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];
    export const PeriodicityEnum = {
        Monthly: 'MONTHLY',
        Bimonthly: 'BIMONTHLY',
        Quarterly: 'QUARTERLY',
        Semiannual: 'SEMIANNUAL',
        Annual: 'ANNUAL',
    } as const;
    export type PeriodicityEnum = typeof PeriodicityEnum[keyof typeof PeriodicityEnum];
    export const EstimationRuleEnum = {
        LastValue: 'LAST_VALUE',
        AverageLast3: 'AVERAGE_LAST_3',
    } as const;
    export type EstimationRuleEnum = typeof EstimationRuleEnum[keyof typeof EstimationRuleEnum];
}


