/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos de una categoría, para el alta y para el cambio de nombre.
 */
export interface CategoryRequest { 
    /**
     * Nombre, único por usuario sin distinguir mayúsculas. Se guarda sin espacios en los extremos.
     */
    name: string;
}

