/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos para cambiar la contraseña del usuario actual.
 */
export interface ChangePasswordRequest { 
    /**
     * Contraseña actual del usuario.
     */
    currentPassword: string;
    /**
     * Contraseña nueva: al menos 10 caracteres, como máximo 72 bytes en UTF-8 y distinta de la actual.
     */
    newPassword: string;
}

