/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Usuario creado. Nunca incluye la contraseña.
 */
export interface CreatedUserResponse { 
    /**
     * Identificador del usuario.
     */
    id?: number;
    /**
     * Email, en minúsculas.
     */
    email?: string;
    /**
     * Período inicial (YYYY-MM).
     */
    startPeriod?: string;
}

