/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos del usuario a crear.
 */
export interface CreateUserRequest { 
    /**
     * Email del usuario. Se guarda en minúsculas y no puede repetirse.
     */
    email: string;
    /**
     * Contraseña inicial: al menos 10 caracteres y como máximo 72 bytes en UTF-8. El usuario deberá cambiarla en su primer ingreso.
     */
    password: string;
    /**
     * Primer período del usuario (YYYY-MM). Si se omite, el período actual. No puede ser posterior al actual.
     */
    startPeriod?: string | null;
}

