/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeletionBlocker } from './deletionBlocker';


/**
 * Lo que haría un alcance.
 */
export interface DeletionPlan { 
    /**
     * Si se puede eliminar: ninguna partida del alcance impide.
     */
    allowed: boolean;
    /**
     * Cuántas partidas se eliminarían.
     */
    entryCount: number;
    /**
     * Período de la primera partida que se eliminaría.
     */
    fromPeriod: string;
    /**
     * Período de la última partida que se eliminaría.
     */
    toPeriod: string;
    /**
     * Qué pasa con el Concepto; nulo si la partida no tiene Concepto.
     */
    itemOutcome?: DeletionPlan.ItemOutcomeEnum | null;
    /**
     * Fin nuevo del Concepto; solo con ENDS_ITEM.
     */
    newEndPeriod?: string | null;
    /**
     * Las partidas del alcance que impiden eliminar, en orden de período.
     */
    blockers: Array<DeletionBlocker>;
}
export namespace DeletionPlan {
    export const ItemOutcomeEnum = {
        KeepsItem: 'KEEPS_ITEM',
        EndsItem: 'ENDS_ITEM',
        RemovesItem: 'REMOVES_ITEM',
    } as const;
    export type ItemOutcomeEnum = typeof ItemOutcomeEnum[keyof typeof ItemOutcomeEnum];
}


