/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Una partida que impide eliminar.
 */
export interface DeletionBlocker { 
    entryId: number;
    period: string;
    /**
     * Por qué una partida impide eliminar. CONSOLIDATED: está consolidada (RN-32), aunque además tenga movimientos. HAS_MOVEMENTS: está pendiente pero tiene movimientos.
     */
    reason: DeletionBlocker.ReasonEnum;
}
export namespace DeletionBlocker {
    export const ReasonEnum = {
        Consolidated: 'CONSOLIDATED',
        HasMovements: 'HAS_MOVEMENTS',
    } as const;
    export type ReasonEnum = typeof ReasonEnum[keyof typeof ReasonEnum];
}


