/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Cambios de una partida (RN-18). Un campo omitido o `null` significa «no cambia»; enviar el mismo valor que ya tiene tampoco es un cambio. Para vaciar la categoría se usa `clearCategory`, porque `null` no distingue «no enviado» de «vaciar». Una partida recurrente no se edita acá: sus datos son los de su Concepto.
 */
export interface EntryUpdateRequest { 
    /**
     * Nombre nuevo. Se guarda sin espacios en los extremos.
     */
    name?: string | null;
    /**
     * El tipo no se edita: solo se acepta el que ya tiene la partida, y uno distinto es 409 FIELD_NOT_EDITABLE.
     */
    kind?: EntryUpdateRequest.KindEnum | null;
    /**
     * Cuenta nueva, del usuario. Con movimientos, solo otra de la misma moneda.
     */
    accountId?: number | null;
    /**
     * Categoría nueva, del usuario.
     */
    categoryId?: number | null;
    /**
     * `true` para dejar la partida sin categoría. Omitido, `null` o `false`, no hace nada. No se combina con `categoryId`.
     */
    clearCategory?: boolean | null;
    /**
     * Vencimiento nuevo: entre el primer día del mes anterior al período de la partida y el último día del período, ambos inclusive.
     */
    dueDate?: string | null;
    /**
     * Presupuestado nuevo, con hasta 2 decimales.
     */
    budgetedAmount?: number | null;
}
export namespace EntryUpdateRequest {
    export const KindEnum = {
        Income: 'INCOME',
        Expense: 'EXPENSE',
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
}


