/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeletionPlan } from './deletionPlan';


/**
 * Qué pasaría al eliminar una partida (HU-18, RN-30 a RN-32), sin modificar nada. Una partida sin Concepto trae solo `removal`; una recurrente, `onlyThis` y `thisAndFuture`. Es la misma regla que aplica la eliminación: si un plan dice `allowed`, `DELETE /api/entries/{id}` lo hace.
 */
export interface EntryDeletionPreview { 
    entryId: number;
    /**
     * Si viene de un Concepto: entonces la eliminación exige un alcance.
     */
    recurring: boolean;
    origin: EntryDeletionPreview.OriginEnum;
    /**
     * Período de la partida.
     */
    period: string;
    /**
     * Eliminar la partida, si no tiene Concepto (RN-30).
     */
    removal?: DeletionPlan;
    /**
     * «Solo este mes», si es recurrente (RN-31).
     */
    onlyThis?: DeletionPlan;
    /**
     * «Este mes y los siguientes», si es recurrente (RN-31).
     */
    thisAndFuture?: DeletionPlan;
}
export namespace EntryDeletionPreview {
    export const OriginEnum = {
        Recurring: 'RECURRING',
        OneOff: 'ONE_OFF',
        CarriedOver: 'CARRIED_OVER',
        ClosingDifference: 'CLOSING_DIFFERENCE',
    } as const;
    export type OriginEnum = typeof OriginEnum[keyof typeof OriginEnum];
}


