/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Si un campo se puede editar y, si no, el motivo.
 */
export interface FieldEditability { 
    editable: boolean;
    /**
     * Motivo en español, solo cuando no es editable.
     */
    reason?: string | null;
}

