/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sesión iniciada: el token y cuándo vence.
 */
export interface LoginResponse { 
    /**
     * JWT para enviar en el header Authorization como «Bearer <token>».
     */
    token: string;
    /**
     * Instante (UTC) en que el token vence: 8 horas después de emitido.
     */
    expiresAt: string;
    /**
     * Si es true, el usuario debe cambiar su contraseña antes de seguir.
     */
    mustChangePassword: boolean;
}

