/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Credenciales para iniciar sesión.
 */
export interface LoginRequest { 
    /**
     * Email del usuario, sin distinguir mayúsculas.
     */
    email: string;
    /**
     * Contraseña del usuario.
     */
    password: string;
}

