/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Un cobro o pago real de una partida (RN-21). El usuario sale del token; la moneda y el signo en el saldo salen de la partida.
 */
export interface MovementRequest { 
    /**
     * Fecha del cobro o pago. No anterior al primer día del período de la partida menos la ventana de anticipación, ni a la apertura de la cuenta; no posterior a hoy; y en un mes que sea un período abierto.
     */
    date: string;
    /**
     * Monto mayor que 0, con hasta 2 decimales.
     */
    amount: number;
    /**
     * Cuenta de donde sale o a donde entra la plata, del usuario. Puede no ser la prevista de la partida, pero tiene que ser de su misma moneda (S-02).
     */
    accountId: number;
    /**
     * Nota opcional. Se guarda sin espacios en los extremos; en blanco es sin nota.
     */
    note?: string | null;
}

