/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Movement } from './movement';
import { PeriodEntry } from './periodEntry';


/**
 * Un movimiento recién registrado y su partida con los valores derivados ya actualizados (real, pendiente, estimado y estado), calculados por el backend.
 */
export interface MovementRegistered { 
    movement: Movement;
    /**
     * La partida, con la misma forma que en la vista del mes. Sigue pendiente (RN-23).
     */
    entry: PeriodEntry;
}

