/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Entre qué fechas admite un movimiento una partida con una cuenta (RN-21). Si `earliestDate` es posterior a `latestDate`, todavía no admite ninguno.
 */
export interface MovementDates { 
    /**
     * La fecha más temprana: la más tardía entre el inicio de la ventana de anticipación y la apertura de la cuenta.
     */
    earliestDate: string;
    /**
     * La fecha más tardía: hoy, según el reloj del backend (no se admiten fechas futuras).
     */
    latestDate: string;
    /**
     * Ventana de anticipación en días: cuántos días antes del inicio del período de la partida se puede fechar un movimiento.
     */
    earlyDays: number;
}

