/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Un cobro o pago real de una partida (RN-21), con su cuenta.
 */
export interface Movement { 
    id: number;
    /**
     * Partida a la que pertenece.
     */
    entryId: number;
    date: string;
    /**
     * Siempre mayor que 0: suma o resta en la cuenta según el tipo de la partida (RN-35).
     */
    amount: number;
    note?: string | null;
    accountId: number;
    accountName: string;
    /**
     * Moneda de la cuenta del movimiento.
     */
    currency: Movement.CurrencyEnum;
}
export namespace Movement {
    export const CurrencyEnum = {
        Ars: 'ARS',
        Usd: 'USD',
    } as const;
    export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];
}


