/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos de una partida puntual (RN-19): algo que pasa una sola vez y figura solo en el período de la ruta.
 */
export interface OneOffEntryRequest { 
    /**
     * Nombre. Se guarda sin espacios en los extremos. Puede repetirse.
     */
    name: string;
    /**
     * Tipo: ingreso o gasto. No se edita después.
     */
    kind: OneOffEntryRequest.KindEnum;
    /**
     * Cuenta prevista, del usuario. Define la moneda de la partida.
     */
    accountId: number;
    /**
     * Categoría del usuario. Opcional.
     */
    categoryId?: number | null;
    /**
     * Vencimiento: entre el primer día del mes anterior al período y el último día del período, ambos inclusive. Puede ser anterior a hoy: la partida nace vencida.
     */
    dueDate: string;
    /**
     * Presupuestado, con hasta 2 decimales.
     */
    budgetedAmount: number;
}
export namespace OneOffEntryRequest {
    export const KindEnum = {
        Income: 'INCOME',
        Expense: 'EXPENSE',
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
}


