/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PeriodCurrencyTotals } from './periodCurrencyTotals';
import { PeriodEntry } from './periodEntry';


/**
 * Vista del mes (HU-15, RN-44): el período, sus partidas separadas en ingresos y gastos, y los totales por moneda. Todos los montos los calcula el backend.
 */
export interface PeriodView { 
    period: string;
    /**
     * OPEN o CLOSED. Un período cerrado se ve igual, pero no admite cambios (RN-09).
     */
    status: PeriodView.StatusEnum;
    /**
     * Período inicial del usuario: no hay períodos anteriores.
     */
    startPeriod: string;
    /**
     * Período actual: el mes de hoy en la zona de la aplicación.
     */
    currentPeriod: string;
    /**
     * Último período que existe para el usuario: no hay períodos posteriores.
     */
    horizon: string;
    /**
     * Partidas de ingreso, por vencimiento, nombre y orden de creación.
     */
    incomes: Array<PeriodEntry>;
    /**
     * Partidas de gasto, por vencimiento, nombre y orden de creación.
     */
    expenses: Array<PeriodEntry>;
    /**
     * Un total por cada moneda que tiene partidas en el período, en el orden ARS, USD. Vacía si el período no tiene partidas. Nunca hay un total que mezcle monedas (RN-04).
     */
    totals: Array<PeriodCurrencyTotals>;
}
export namespace PeriodView {
    export const StatusEnum = {
        Open: 'OPEN',
        Closed: 'CLOSED',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


