/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Una partida en la vista del mes, con sus valores derivados (RN-16, RN-17, RN-20).
 */
export interface PeriodEntry { 
    id: number;
    /**
     * Concepto del que viene; nulo si no es recurrente.
     */
    budgetItemId?: number | null;
    origin: PeriodEntry.OriginEnum;
    kind: PeriodEntry.KindEnum;
    /**
     * En una partida recurrente, el nombre de su Concepto.
     */
    name: string;
    categoryId?: number | null;
    /**
     * En una partida recurrente, la categoría de su Concepto.
     */
    categoryName?: string | null;
    accountId: number;
    accountName: string;
    /**
     * Moneda de la partida: la de su cuenta (RN-04).
     */
    currency: PeriodEntry.CurrencyEnum;
    /**
     * Vencimiento. Puede caer en el mes anterior al período (desfase −1).
     */
    dueDate: string;
    /**
     * Número de cuota; nulo si no es en cuotas.
     */
    installmentNumber?: number | null;
    /**
     * Total de cuotas de su Concepto; nulo si no es en cuotas.
     */
    installmentsTotal?: number | null;
    budgetedAmount: number;
    /**
     * Real: suma de sus movimientos.
     */
    actualAmount: number;
    /**
     * Pendiente: presupuestado menos real, nunca negativo; 0 si está consolidada.
     */
    pendingAmount: number;
    /**
     * Estimado: real más pendiente; en una consolidada, el monto consolidado.
     */
    forecastAmount: number;
    /**
     * ESTIMATED: pendiente sin movimientos. PARTIAL: pendiente con movimientos. CONSOLIDATED: consolidada.
     */
    status: PeriodEntry.StatusEnum;
    /**
     * Partida editada: el usuario cambió a mano su presupuestado.
     */
    manual: boolean;
    /**
     * Vencida: pendiente y con vencimiento anterior a hoy.
     */
    overdue: boolean;
}
export namespace PeriodEntry {
    export const OriginEnum = {
        Recurring: 'RECURRING',
        OneOff: 'ONE_OFF',
        CarriedOver: 'CARRIED_OVER',
        ClosingDifference: 'CLOSING_DIFFERENCE',
    } as const;
    export type OriginEnum = typeof OriginEnum[keyof typeof OriginEnum];
    export const KindEnum = {
        Income: 'INCOME',
        Expense: 'EXPENSE',
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
    export const CurrencyEnum = {
        Ars: 'ARS',
        Usd: 'USD',
    } as const;
    export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];
    export const StatusEnum = {
        Estimated: 'ESTIMATED',
        Partial: 'PARTIAL',
        Consolidated: 'CONSOLIDATED',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


