/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Totales de los ingresos o de los gastos de una moneda.
 */
export interface PeriodSideTotals { 
    /**
     * Cuántas partidas suma. Con 0, la moneda no tiene partidas de ese tipo y todos los montos son 0.
     */
    entryCount: number;
    budgetedAmount: number;
    actualAmount: number;
    pendingAmount: number;
    forecastAmount: number;
}

