/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PeriodSideTotals } from './periodSideTotals';


/**
 * Totales de una moneda en el período (RN-44).
 */
export interface PeriodCurrencyTotals { 
    currency: PeriodCurrencyTotals.CurrencyEnum;
    /**
     * Totales de las partidas de ingreso.
     */
    income: PeriodSideTotals;
    /**
     * Totales de las partidas de gasto.
     */
    expense: PeriodSideTotals;
    /**
     * Resultado: estimado de ingresos menos estimado de gastos. Puede ser negativo.
     */
    result: number;
}
export namespace PeriodCurrencyTotals {
    export const CurrencyEnum = {
        Ars: 'ARS',
        Usd: 'USD',
    } as const;
    export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];
}


