/**
 * Smartcoin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datos para restablecer la contraseña de un usuario.
 */
export interface ResetPasswordRequest { 
    /**
     * Email del usuario, sin distinguir mayúsculas.
     */
    email: string;
    /**
     * Contraseña temporal: al menos 10 caracteres y como máximo 72 bytes en UTF-8. El usuario deberá cambiarla en su próximo ingreso.
     */
    temporaryPassword: string;
}

